[Youtube]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
excluded-patches = "'Alternative thumbnails' 'Return YouTube Dislike' 'Custom branding'"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"
apkmirror-dpi = "480dpi"
included-patches = "'Limit feed to followed profiles' 'Anonymous story viewing' 'Hide highlights tray' 'Hide suggested content' 'Enable developer menu' 'Open links externally' 'Disable signature check' 'Disable story auto flipping'"
patcher-args = "-e 'Hide navigation buttons' -OhideCreate=true"
